version: '3'

services:
  traefik:
    image: "traefik"
    #    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  php-apache:
    image: "php:7.4-apache"
    container_name: "phpapache"
    restart: "no"
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "remote_port= 9000 remote_autostart=1"
    #    env_file:
    #      - ./Docker_config/apache/php_ini_conf.env
    labels:
      - "traefik.http.routers.php.rule=Host(`php.docker.syrgoma.com`)"
      - "traefik.http.routers.my-entrypoint-two.entrypoints=web"
    volumes:
      - "./symfony:/var/www/html"

  composer:
    image: composer
    command: install
    working_dir: /app
    volumes:
      - "./symfony:/app"

  db:
    image: mysql
    volumes:
      - "./mysql-data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: pari_sportif_db
      MYSQL_USER: pari_user
      MYSQL_PASSWORD: pari_pass

  phpmyadmin:
    image: "phpmyadmin"
    environment:
      PMA_HOST: "db"
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.syrgoma.com`)"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.syrgoma.com`)"
      - "traefik.http.routers.my-entrypoint-one.entrypoints=web"