version: '3'

services:
  traefik:
    #container_name: "traefik"
    image: "traefik"
    restart: "always"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  php-apache:
    #container_name: "phpapache"
    build:
      context: .
      dockerfile: "Dockerfile-php7.4-apache"
    image: "acs-cda2020-3/php-apache" # nomme l'image build plus haut au lieu de la télécharger !
    restart: "always"
    environment:
      # OpCache
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_MAX_ACCELERATED_FILES: "10000"
      PHP_OPCACHE_MEMORY_CONSUMPTION: "192"
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: "10"

      # Xdebug
      PHP_XDEBUG_REMOTE_ENABLE: "1"
      PHP_XDEBUG_REMOTE_HOST: "localhost"
      PHP_XDEBUG_REMOTE_PORT: "9000"
      PHP_XDEBUG_IDE_KEY: "PHPSTORM"

      # Autre
      #env_file:
        #- ./Docker_config/apache/php_ini_conf.env
    labels:
      - "traefik.http.routers.php.rule=Host(`php.docker.syrgoma.com`)"
      - "traefik.http.routers.php.entrypoints=web"
    volumes:
      - "./symfony:/var/www/html"

  composer:
    #container_name: "composer"
    image: "composer"
    restart: "no"
    working_dir: "/app"
    command: "install"
    volumes:
      - "./symfony:/app"

  db:
    #container_name: "db"
    image: "mysql"
    restart: "always"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "pari_sportif_db"
      MYSQL_USER: "pari_user"
      MYSQL_PASSWORD: "pari_pass"
    volumes:
      - "./mysql-data:/var/lib/mysql"

  phpmyadmin:
    #container_name: "phmyadmin"
    image: "phpmyadmin"
    environment:
      PMA_HOST: "db"
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.syrgoma.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"

  #TODO Supprimer quand n'est plus nécessaire
  whoami:
    container_name: "simple-service"
    image: "traefik/whoami"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.syrgoma.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mh.docker.syrgoma.com`)"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "traefik.http.routers.mailhog.loadbalancer.server.port=8025"