@startuml

package "BDD" <<DataBase>> {

    class Utilisateur {
        - int ID
        - nom
        - prénom
        - pseudo
        - mail
        - mdp
    }
    class Pari {
        - ID
        - montant
        - statut
        - évènement_ID
        - user_ID
    }
    class Sport {
        - ID
        - nom
        - type_sport_ID
    }
    class Porte_Feuille{
    }
    class Epreuve{
    }
    class Type_sport{
    }
    class Évènement{
    }
    class Historique_PorteFeuille{
    }
    class Historique_Pari{
    }
    class Epreuve_Event{
    }
}


namespace Class{
        class Utilisateur{
        }
        class Pari{
        }
}
@enduml

