name: PHPUnit

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./symfony

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP with extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: pdo_mysql

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit tests
        uses: php-actions/phpunit@v8
        with:
          configuration: ./symfony/phpunit.xml.dist
